### ISSUE TITLE
Falha ao executar Nubank

### ISSUE THREAD

**Issue by ftgo** [maxiwell/ofx-bot#12]
OS: Ubuntu 16.04 x86_64
ofx-bot: nightly-2016-03-22/7.10.3

em 06/06/2016 às 22:48.

`
Iniciando Selenium Server
Efetuando login
Erro durante a execuçãoFailedCommand ElementNotVisible 
Session: SessionId "d980aad5-6af9-4595-bd1c-7cba70f32d97" at "127.0.0.1":4444
org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'sarue', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-22-generic', java.version: '1.7.0_79'
Driver info: driver.version: unknown
  <anonymous class>.fxdriver.preconditions.visible (file:///tmp/anonymous2816778135061828114webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9615)
  <anonymous class>.DelayedCommand.prototype.checkPreconditions_ (file:///tmp/anonymous2816778135061828114webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12265)
  <anonymous class>.DelayedCommand.prototype.executeInternal_/h (file:///tmp/anonymous2816778135061828114webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12282)
  <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/anonymous2816778135061828114webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:603)
Desligando Selenium Server
`

**Comment by maxiwell** [comment]
Em qual resolução está sendo executado o firefox?

**Comment by ftgo** [comment]
1600x900 (16:9 Full HD)

**Comment by maxiwell** [comment]
Percebi esse problema em algumas resoluções. Em Full HD (1920x1080) acontece o mesmo erro?

**Comment by ftgo** [comment]
Percebi que não é a resolução mas sim quando a tela do Firefox não está maximizada. Se iniciar não maximizada é só fazer manualmente, durante a execução.

**Comment by maxiwell** [comment]
Sim, o problema é a resolução do firefox, não do monitor. Tem como garantir no selenium que o firefox sempre inicie maximizado. Depois farei essa alteração.

**Comment by francesquini** [comment]
Após o novo pull request (https://github.com/maxiwell/ofx-bot/pull/16), por padrão o NuBank agora roda com o Chrome. Ele inicia maximizado entre outras melhorias. Me avise se foi o suficiente para resolver este problema.

**Comment by francesquini** [comment]
Quem cala consente :-)
