### ISSUE TITLE
[Nubank] Formato de data incorreto

### ISSUE THREAD

**Issue by ftgo** [maxiwell/ofx-bot#13]
As datas de anos anteriores estão sendo extraídas incorretamente. Parece ser um problema não usar a `label` da aba, pois o Nubank não exibe em qualquer outro lugar de que fatura se trata.

Aba **DEZ 15**:

`
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20161215100000[-03:EST]
<TRNAMT>-19.90
<FITID>Venc. 10 JAN
<CHECKNUM>Venc. 10 JAN
<MEMO>Netflix Com
</STMTTRN>
`

Aba **NOV 15**:
`
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20161115100000[-03:EST]
<TRNAMT>-19.90
<FITID>Venc. 10 DEZ
<CHECKNUM>Venc. 10 DEZ
<MEMO>Netflix Com
</STMTTRN>
`

**Comment by francesquini** [comment]
Acabo de fazer um pull request https://github.com/maxiwell/ofx-bot/pull/16 que espero que resolva este problema. Estou com dificuldades para testar já que a minha primeira fatura é de fev de 2016. Avisem caso ainda não funcione.

**Comment by francesquini** [comment]
Agora que a minha fatura atravessa pra 2017, consegui reproduzir o problema. Resolvido na f9d798f1efdc5cc65153c05ff696c58bb40aaee4
