### ISSUE TITLE
[Nubank] Falha na navegação de múltiplas abas de faturas

### ISSUE THREAD

**Issue by ftgo** [maxiwell/ofx-bot#14]
Na página de faturas, tenho 14 abas: de **AGO 15** a **SET** (ano corrente, ou seja, 2016). Contudo só foi extraído até **MAR** (ano corrente). Suspeito que seja por não entender o scroll horizontal.

**Comment by maxiwell** [comment]
Este bug não consegui reproduzir. Na issue #13 você cita erros de data para anos anteriores (bug conhecido). Então suponho que você conseguiu navegar até Nov 15.  Nesta issue o erro acontece em Mar 16. O comportamento do NuBank está não-determinístico pra você?

**Comment by ftgo** [comment]
Na verdade é determinístico sim. 

O bot faz as operações na seguinte ordem: **MAR**, **FEV**, ..., **AGO 15**. Ignora meses antes de **AGO 15** e depois de **MAR**. Isto se dá porque alguns destes meses estão ocultos na barra de rolagem horizontal.

O ideal é que pegue todas as abas disponíveis, mesmo as futuras, iniciando do mais novo até que o item atual não seja alterado, ou seja, o mês mais antigo esteja selecionado para visualização.

**Comment by francesquini** [comment]
Sim, aparentemente o método sendo utilizado agora para obter todas as abas abertas não funciona muito bem quando se possui muitas faturas. Está complicado replicar o erro para tentar resolver já que a minha fatura mais antiga é de fev/2016....

**Comment by francesquini** [comment]
Este bug deve estar corrigido na versão mais nova ( > db3ee071eaea3204dfb74da0f62482b8841a62f0). Reabra caso o problema persista.

**Comment by francesquini** [comment]
Incorretamente eu havia assumido que as abas eram numeradas em hexa, com 3 dígitos. Aparentemente não é o que ocorre. Na minha atualmente elas vão até '00H'.

**Comment by francesquini** [comment]
O código foi mudado (> b1016a24f95740c437de60525d7a554c6b119a6e) para gerar a numeração das abas (necessária à navegação) em base 36 (0-9A-Z). Se alguém tiver algum exemplo com mais de 36 faturas geradas e puder confirmar se a numeração é realmente base 36 (ou talvez quem sabe seja base 64) por favor nos informem ou reabram a issue!
