### ISSUE TITLE
[Nubank] Falha quando a fatura possui muitos registros

### ISSUE THREAD

**Issue by ftgo** [maxiwell/ofx-bot#15]
Quando a fatura tem muitos registros e o scroll vertical é visível, os registros não exibidos são ignorados.

**Comment by francesquini** [comment]
Eu tenho alguns exemplos onde a fatura tem dezenas de registros e tem um scroll vertical considerável (3 páginas completas +-). Esse comportamento é deterministico?

Fico imaginando se não é reflexo dos outros problemas com o NuBank/Firefox reportados nos demais issues....

**Comment by francesquini** [comment]
A série mais recente de modificações mudou bastante o funcionamento da obtenção dos elementos da fatura. Não foi mais observado o problema.
