### ISSUE TITLE
Suporte a contas pessoa jurídica e execução em servidores sem GUI

### ISSUE THREAD

**Issue by renanwilliam** [maxiwell/ofx-bot#22]
Seria muito interessante adicionar suporte as contas pessoas jurídicas e para serem executados em servidores sem interface gráfica - vi algo nesse [link ](http://www.alittlemadness.com/2008/03/05/running-selenium-headless/)sobre o caso. Isso ajudaria muito pequenas empresas a fazerem conciliação bancária.

**Comment by renanwilliam** [comment]
Acredito que referente ao procedimento de executar em servidores sem GUI a solução seja essa:
`apt-get install xvfb firefox`
`xvfb-run python ./ofx-santander-pj.py`

Fonte: [http://elementalselenium.com/tips/38-headless](http://elementalselenium.com/tips/38-headless)

**Comment by francesquini** [comment]
@renanwilliam essa é justamente a solução descrita em https://github.com/maxiwell/ofx-bot/blob/master/README-ptbr.md#como-usar

Note os parâmetros adicionais de resolução. Alguns sites de bancos mudam o formato da página dependendo da resolução e sem esses parâmetros o script pode falhar.

**Comment by renanwilliam** [comment]
@francesquini sim, verdade! o ponto principal desse issue acho que é o mapeamento para contas PJ, que coloquei na pull request #23

**Comment by francesquini** [comment]
@renanwilliam ok! Já comecei uma discussão por lá para podermos prosseguir com o merge.
