### ISSUE TITLE
cp: cannot stat when build

### ISSUE THREAD

**Issue by jeanyuk** [maxiwell/ofx-bot#24]
Hello contributors, congratulations for the initiative.
I was interested to test the bot but after run build, I got the following error in my console:

`cp: cannot stat '/build/ofx-itau/ofx-itau': No such file or directory`

Any idea of what might be?

**Comment by francesquini** [comment]
Are you sure there was no other problem reported before (during the build process)? 

This error simply means the executable was not found. Surely something wrong happened during the build...

**Comment by jeanyuk** [comment]
This ran during the process build, see my screen

![afd720d946124c0a81019c3cc785e146](https://cloud.githubusercontent.com/assets/1505326/24842566/c78589f4-1d6f-11e7-9a5b-8c6e5c2fa46b.png)

**Comment by francesquini** [comment]
Do you have `stack` installed on your machine?

If not, see here: https://docs.haskellstack.org/en/stable/README/

If yes, try to run this (inside itau directory) and verify if it runs without errors:
```
stack update
stack build
```
if it doesn't work, you might have an old version of stack ( `stack --version`, mine is 1.4.0) . Run `stack install stack` to upgrade. Don't forget to add the path informed at the end of the installation to your path.

**Comment by jeanyuk** [comment]
Yes I have stack already installed, but after upgrade with your recommendation and
replace path with my path I got this:

![88888888888](https://cloud.githubusercontent.com/assets/1505326/24842997/bbbbd556-1d74-11e7-8448-0ad289fe57b9.png)

It's right, normal?
Thanks for attention

**Comment by francesquini** [comment]
What is the output of `stack build`?

**Comment by jeanyuk** [comment]
`ubuntu@:~/ofx-bot/itau$ stack build
Populating index cache ...Killed`

**Comment by jeanyuk** [comment]
Dear francisquini, I got it.
My server was dying by memory. I did a fix increasing more.
Thank you again 和

**Comment by francesquini** [comment]
👍
