### ISSUE TITLE
Permitir que CPF também seja passado via stdin

### ISSUE THREAD

**Issue by ggondim** [maxiwell/ofx-bot#5]

**Comment by francesquini** [comment]
Todos os programas já recebem os dados via stdin. Você já pode fazer isso usando "|" ou "<" como o exemplo do readme. Isso não está funcionando para você?

**Comment by ggondim** [comment]
No OFX do Santander não está funcionando. Dei uma fuçada no py e parece que realmente só a senha ele pega do cfg.

**Comment by maxiwell** [comment]
Eu uso o santander via redirecionamento de arquivo. Coloco o CPF na primeira linha e a senha na segunda, e executo:

``` bash
./ofx-santander.py < input.cfg
```

Isso está falhando com vc?

**Comment by ggondim** [comment]
Sim, estava falhando. Ao que parece era um problema com o meu Python. Atualmente a versão desse script não funciona com a versão 3 do Python.

Também ocasionalmente estava acontecendo um problema com o "iframePrinc" que não era encontrado pelo Selenium, mas aumentei o sleep e até agora não ocorreu de novo.

Se quiserem podem fechar essa issue também. Vou fazer um fork e request das minhas alterações, se aceitarem. Vocês pretendem mudar todos os scripts para o Python 3?

**Comment by maxiwell** [comment]
Esses tempos dos sleeps são sensíveis à velocidade da internet. Então as vezes precisa personalizar. Fiz algumas mudanças para ficar aguardando um determinado campo aparecer ao invés de usar o sleep. Mas ainda não está 100%. 

Seria legal passar os scripts para Python 3. Alterações são bem vindas sim.
