### ISSUE TITLE
Permitir que CPF e senha sejam passados por argumentos na linha de comando

### ISSUE THREAD

**Issue by ggondim** [maxiwell/ofx-bot#6]

**Comment by francesquini** [comment]
O problema de passar senhas por linha de comando é que qualquer outro usuário da mesma máquina vai poder fazer um simples "ps" e vai conseguir visualizar os dados de login. Isso é bem inseguro...

Se você quer muito fazer isso, você já pode fazer com 

`printf "%s\n" dado1 dado2 | QUALQUER_UM_DOS_OFX`

Esse método, porém, tem as mesmas falhas de segurança.... Sem falar no historico de comandos do bash que vai guardar as senhas abertas...

**Comment by ggondim** [comment]
Acho que então só o .cfg por stdin seja suficiente. Concordo com seu ponto de vista de segurança.
