### ISSUE TITLE
Dependências do Gentoo

### ISSUE THREAD

**Issue by saboya** [maxiwell/ofx-bot#7]
Não é um bug, mas apenas uma ajuda pra quem usa Gentoo: Os pacotes stable no momento não são suficientes pra compilar o ofx-bot, então é necessário dar unmask em alguns pacotes. No caso eu também estou usando a haskell overlay. Então, basicamente, seria isso:

Adicione a haskell overlay usando o layman:
`
layman -a haskell
`

Crie um set com as dependências necessárias (coloque o conteúdo a seguir no arquivo `/etc/portage/sets/ofx-bot` ou outro nome de sua preferência):

```
dev-python/selenium
www-client/firefox-bin
=dev-lang/ghc-7.10.3 ~amd64
=dev-haskell/haskell-platform-2014.2.0.0 ~amd64
=dev-haskell/nats-1.1 ~amd64
=dev-haskell/haddock-2.16.1 ~amd64
=dev-haskell/transformers-0.4.3.0 ~amd64
=dev-haskell/mtl-2.2.1-r1 ~amd64
=dev-haskell/cabal-1.22.8.0 ~amd64
=dev-haskell/cabal-install-1.22.8.0 ~amd64
=dev-haskell/unordered-containers-0.2.7.0 ~amd64
=dev-haskell/parallel-3.2.1.0 ~amd64
=dev-haskell/semigroups-0.18.1 ~amd64
=dev-haskell/hashable-1.2.4.0 ~amd64
=dev-haskell/async-2.1.0 ~amd64
=dev-haskell/primitive-0.6.1.0-r1 ~amd64
=dev-haskell/case-insensitive-1.2.0.6 ~amd64
=dev-haskell/haddock-api-2.16.1 ~amd64
```

Depois basta dar emerge no set:
`
emerge @ofx-bot
`

**Comment by francesquini** [comment]
Apesar da documentação ainda não estar atualizada, os últimos commits passaram a permitir a compilação com o stack. Além de ser bem mais rápido por usar pacotes pré-compilados, ele costuma resolver sozinho todo esse tipo de problema, incluindo  a instalação do GHC.

Eu não tenho nenhum Gentoo para testar aqui, você poderia confirmar se o stack está disponível como pacote no Gentoo e se ele dá conta do recado?

Para compilar neste caso bastaria:

`stack build`

dentro do diretório do nubank. No caso do itau também será preciso um:

```
git submodule init
git submodule update
```

antes de compilar para garantir que a lib foi baixada.

**Comment by saboya** [comment]
Stack seria o http://www.haskellstack.org/? Se for, não está disponível na árvore de pacotes padrão, mas está disponível sim na haskell overlay. Posso testar depois.

Mas, resolvendo as dependências, a instalação fica rápida no Gentoo pois ele compila os pacotes da distro quando instala, e depois pra compilar o ofx já está tudo pronto. O problema é que vários pacotes que a aplicação precisa estão marcados como unstable no Gentoo ainda, então você acaba tendo que dar unmask manualmente (no meu caso que quero ficar no stable). Inclusive abri uma issue pros caras e eles adicionaram o webdriver na overlay, que também não tinha.

Dá pra só puxar o GHC / cabal e fazer tudo pelo cabal, mas não é o recomendado pelos maintainers. Eu estou escrevendo um ebuild pra facilitar tudo, assim que terminar posso colocar aqui pra quem precisar.

obrigado pela atenção!

**Comment by francesquini** [comment]
Sim, é este stack mesmo...

Legal! Contribuições são sempre bem-vindas...
