### ISSUE TITLE
ofx-nubank: fd:5: hGetLine: end of file

### ISSUE THREAD

**Issue by diegofcv** [maxiwell/ofx-bot#9]
Opa, legal o projeto! Estou tentando usar aqui, em especial o Nu-Bank. Ele compilou OK, após a satisfação de todas as dependências, mas na hora de executar ele só lança essa mensagem aí:
ofx-nubank: fd:5: hGetLine: end of file
Em certa tentativa a janela do FF chegou a abrir, depois nem isso. Foi criado um arquivo de log, mas ele só apresenta o conteúdo "NPP_GetValue is called". 
Precisando de informações adicionais, basta me dizer quais são.

**Comment by maxiwell** [comment]
Verifique se tem algum servidor selenium em execução:

``` bash
ps aux | grep selenium
```

Se tiver, encerre-o e tente executar o `ofx-nubank` novamente.

**Comment by francesquini** [comment]
Em alguns casos quando há uma exceção durante a execução, o servidor selenium pode acabar ficando no ar e as próximas execuções vão falhar enquanto ele não tiver sido morto. É um bug já conhecido, vou corrigi-lo em breve. 

Por hora, você pode usar o workaround sugerido pelo @maxiwell.
